name: "Emu PR"

on:
  pull_request:
    branches: ["dev"]
    paths-ignore:
      - "**/*.md"
      - "dev.notes/**"
      - "post_build/**"
      - "z_original_repo_files/**"
      - "sdk/*.txt"
      - "LICENSE"
      - "tools/generate_emu_config/**"
      - "tools/migrate_gse/**"
      - "tools/steamclient_loader/**"

permissions:
  contents: "write"

jobs:
  emu-linux:
    name: "Linux"
    uses: "./.github/workflows/emu-build-all-linux.yml"

  emu-win:
    name: "Windows VS22"
    uses: "./.github/workflows/emu-build-all-win-vs22.yml"

  emu-win-cross:
    name: "Windows cross"
    uses: "./.github/workflows/emu-build-all-win-cross.yml"
