name: "Build emu (Windows VS latest)"

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: "write"

jobs:
  build:
    name: "MSVC VS latest"
    runs-on: "windows-2025"
    strategy:
      fail-fast: false
      matrix:
        cfg: ["Debug", "Release"]

    steps:
      - uses: actions/checkout@v6

      - name: Ensure LF line ending
        shell: cmd
        run: |
          git config --local core.autocrlf false
          git config --system core.autocrlf false
          git config --global core.autocrlf false

      - name: Configure
        shell: cmd
        run: |
          cmake -S . -B build/win -G "Visual Studio 18 2026" -DCMAKE_BUILD_TYPE=${{ matrix.cfg }}

      - name: Build
        shell: cmd
        run: |
          cmake --build build/win --config ${{ matrix.cfg }} -j ${{ env.CMAKE_BUILD_PARALLEL_LEVEL || 4 }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: "emu-win-${{ matrix.cfg }}-${{ github.sha }}"
          path: "build/win/"
          if-no-files-found: "error"
          compression-level: 9
          retention-days: 7
