name: "Build emu (Linux cross-compile to Windows)"

on:
  push:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: "write"

jobs:
  build:
    name: "clang-cl + msvc-wine"
    runs-on: "ubuntu-24.04"
    strategy:
      fail-fast: false
      matrix:
        cfg: ["Release", "Debug"]

    container:
      image: archlinux:latest

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm archlinux-keyring
          pacman -Syu --noconfirm base-devel sudo git clang lld ninja make cmake extra-cmake-modules python wine msitools ca-certificates libwbclient

      - name: Install msvc-wine
        run: |
          export WINDOWS_SDK_PATH=/opt/msvc
          mkdir -p $WINDOWS_SDK_PATH
          export WINE=$(command -v wine64 || command -v wine || false)
          $WINE wineboot
          git clone https://github.com/mstorsjo/msvc-wine
          ./msvc-wine/vsdownload.py --accept-license --dest $WINDOWS_SDK_PATH
          ./msvc-wine/install.sh $WINDOWS_SDK_PATH

      - name: Build
        run: |
          export WINDOWS_SDK_PATH=/opt/msvc
          export PATH=$WINDOWS_SDK_PATH/bin/x64:$PATH
          ./build_windows.sh ${{ matrix.cfg }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: "emu-win-cross-${{ matrix.cfg }}-${{ github.sha }}"
          path: "build/windows/"
          if-no-files-found: "error"
          compression-level: 9
          retention-days: 7
